version: '3.9'

services:
 expressapp: 
    container_name: nodeJS
    image: node:14.17.0
    ports:
      - 4000:4000
    working_dir: /src/app
    volumes:
      - './src:/src/app'
      - './node_modules:/app/node_modules'
    command: npm start:debug  
 reactapp:
    container_name: react
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ':/client/src/app'
 db:
    container_name: postgres_container
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_DATABASE: transactionsdb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data 
 pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
  


